-- ═══ Ziyaretçi/sayfa görüntüleme takibi ═══
-- Kendi Supabase altyapımızda, üçüncü taraf servis yok.

create table if not exists page_views (
  id bigint generated by default as identity primary key,
  path text not null,
  referrer text,
  user_id uuid references auth.users(id) on delete set null,
  session_id text not null,
  timezone text,
  device_type text,      -- 'mobile' | 'desktop'
  platform text,         -- 'web' | 'ios' | 'android'
  created_at timestamptz not null default now()
);

create index if not exists idx_page_views_created_at on page_views (created_at desc);
create index if not exists idx_page_views_path on page_views (path);

alter table page_views enable row level security;

-- Herkes (giriş yapmamış ziyaretçiler dahil) kayıt EKLEYEBİLİR — kimse okuyamaz, sadece yazabilir.
drop policy if exists "page_views_insert_anyone" on page_views;
create policy "page_views_insert_anyone"
  on page_views for insert
  with check (true);

-- Sadece admin rolündeki kullanıcılar istatistikleri GÖREBİLİR.
drop policy if exists "page_views_select_admin" on page_views;
create policy "page_views_select_admin"
  on page_views for select
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );
