-- TELİFLİ OLABİLECEK SÖZLERİ GENEL KATALOGDA GİZLEME (2026-10-09)
--
-- NEDEN: Apple App Review 2.1, soru 6 ("korunan üçüncü taraf içerik varsa yetki belgesi"). Lisansımız (MESAM/MSG)
-- yok. Genel katalogdaki 784 eserin hepsinde söz vardı; bunların büyük kısmı ekip tarafından içe aktarılmış.
-- KURAL (İngilizce eserler hariç — onlar kamu malı diye seçildi, bkz. _ingilizce_eserler/notlar.json):
--   modern tür (Özgün, Türk Pop, Arabesk/Fantezi, TSM, Türk Rock, Şiir, Diğer) · türü girilmemiş ·
--   THM ama besteci ya da söz yazarı adlı (anonim değil).
-- Toplam 368 eser: modern 73, türsüz 109, adlı 186.
-- Söz, akor (akor sayfası sözü de içerir) ve nota SİLİNMEZ: works_telif_yedek'e taşınır, works'te boşaltılır.
-- Künye (ad, makam, usul, yöre...) yerinde kalır; kullanıcı kendi kopyasına kendi sözünü ekleyebilir.
-- GERİ AÇMA: yalnız lisans/izin alınan eser için (aşağıdaki GERİ AÇMA bloğu, id listesiyle).

create table if not exists public.works_telif_yedek as
  select id as work_id, lyrics, chords, nota_url, nota_pages, now() as gizlendi_at, ''::text as neden
  from public.works where false;
alter table public.works_telif_yedek enable row level security;   -- politika yok: yalnız SQL Editor / service_role
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'works_telif_yedek_pkey') then
    alter table public.works_telif_yedek add constraint works_telif_yedek_pkey primary key (work_id);
  end if;
end $$;

with liste(work_id, neden) as (values
  (44,'modern tür'),
  (47,'modern tür'),
  (60,'modern tür'),
  (66,'modern tür'),
  (67,'modern tür'),
  (71,'modern tür'),
  (90,'modern tür'),
  (124,'modern tür'),
  (130,'modern tür'),
  (136,'modern tür'),
  (137,'modern tür'),
  (138,'modern tür'),
  (153,'modern tür'),
  (157,'modern tür'),
  (183,'modern tür'),
  (188,'modern tür'),
  (190,'modern tür'),
  (204,'modern tür'),
  (208,'modern tür'),
  (222,'modern tür'),
  (236,'modern tür'),
  (257,'modern tür'),
  (268,'modern tür'),
  (269,'modern tür'),
  (271,'modern tür'),
  (272,'modern tür'),
  (274,'modern tür'),
  (275,'modern tür'),
  (277,'modern tür'),
  (296,'modern tür'),
  (299,'modern tür'),
  (303,'modern tür'),
  (308,'modern tür'),
  (314,'modern tür'),
  (315,'modern tür'),
  (319,'modern tür'),
  (330,'modern tür'),
  (331,'modern tür'),
  (335,'modern tür'),
  (336,'modern tür'),
  (357,'modern tür'),
  (359,'modern tür'),
  (360,'modern tür'),
  (373,'modern tür'),
  (386,'modern tür'),
  (389,'modern tür'),
  (393,'modern tür'),
  (395,'modern tür'),
  (396,'modern tür'),
  (406,'modern tür'),
  (407,'modern tür'),
  (428,'modern tür'),
  (433,'modern tür'),
  (509,'modern tür'),
  (534,'modern tür'),
  (535,'modern tür'),
  (536,'modern tür'),
  (538,'modern tür'),
  (542,'modern tür'),
  (1805,'modern tür'),
  (1868,'modern tür'),
  (1895,'modern tür'),
  (1914,'modern tür'),
  (1915,'modern tür'),
  (1923,'modern tür'),
  (1924,'modern tür'),
  (1926,'modern tür'),
  (1931,'modern tür'),
  (1937,'modern tür'),
  (1938,'modern tür'),
  (1942,'modern tür'),
  (1943,'modern tür'),
  (1944,'modern tür'),
  (9,'türsüz'),
  (14,'türsüz'),
  (27,'türsüz'),
  (35,'türsüz'),
  (40,'türsüz'),
  (43,'türsüz'),
  (46,'türsüz'),
  (51,'türsüz'),
  (63,'türsüz'),
  (69,'türsüz'),
  (70,'türsüz'),
  (77,'türsüz'),
  (78,'türsüz'),
  (89,'türsüz'),
  (102,'türsüz'),
  (107,'türsüz'),
  (108,'türsüz'),
  (110,'türsüz'),
  (112,'türsüz'),
  (119,'türsüz'),
  (127,'türsüz'),
  (128,'türsüz'),
  (129,'türsüz'),
  (133,'türsüz'),
  (142,'türsüz'),
  (143,'türsüz'),
  (146,'türsüz'),
  (148,'türsüz'),
  (151,'türsüz'),
  (159,'türsüz'),
  (161,'türsüz'),
  (164,'türsüz'),
  (165,'türsüz'),
  (180,'türsüz'),
  (182,'türsüz'),
  (189,'türsüz'),
  (192,'türsüz'),
  (193,'türsüz'),
  (194,'türsüz'),
  (195,'türsüz'),
  (197,'türsüz'),
  (206,'türsüz'),
  (210,'türsüz'),
  (211,'türsüz'),
  (214,'türsüz'),
  (217,'türsüz'),
  (219,'türsüz'),
  (225,'türsüz'),
  (228,'türsüz'),
  (255,'türsüz'),
  (259,'türsüz'),
  (260,'türsüz'),
  (261,'türsüz'),
  (266,'türsüz'),
  (270,'türsüz'),
  (273,'türsüz'),
  (276,'türsüz'),
  (279,'türsüz'),
  (281,'türsüz'),
  (283,'türsüz'),
  (286,'türsüz'),
  (287,'türsüz'),
  (290,'türsüz'),
  (294,'türsüz'),
  (306,'türsüz'),
  (307,'türsüz'),
  (310,'türsüz'),
  (317,'türsüz'),
  (320,'türsüz'),
  (321,'türsüz'),
  (324,'türsüz'),
  (327,'türsüz'),
  (332,'türsüz'),
  (337,'türsüz'),
  (340,'türsüz'),
  (341,'türsüz'),
  (344,'türsüz'),
  (353,'türsüz'),
  (354,'türsüz'),
  (358,'türsüz'),
  (361,'türsüz'),
  (366,'türsüz'),
  (372,'türsüz'),
  (375,'türsüz'),
  (385,'türsüz'),
  (390,'türsüz'),
  (391,'türsüz'),
  (392,'türsüz'),
  (394,'türsüz'),
  (399,'türsüz'),
  (401,'türsüz'),
  (402,'türsüz'),
  (408,'türsüz'),
  (427,'türsüz'),
  (429,'türsüz'),
  (430,'türsüz'),
  (431,'türsüz'),
  (432,'türsüz'),
  (435,'türsüz'),
  (510,'türsüz'),
  (520,'türsüz'),
  (525,'türsüz'),
  (528,'türsüz'),
  (537,'türsüz'),
  (1911,'türsüz'),
  (1912,'türsüz'),
  (1913,'türsüz'),
  (1925,'türsüz'),
  (1929,'türsüz'),
  (6,'adlı besteci/söz yazarı'),
  (10,'adlı besteci/söz yazarı'),
  (15,'adlı besteci/söz yazarı'),
  (17,'adlı besteci/söz yazarı'),
  (18,'adlı besteci/söz yazarı'),
  (19,'adlı besteci/söz yazarı'),
  (20,'adlı besteci/söz yazarı'),
  (21,'adlı besteci/söz yazarı'),
  (22,'adlı besteci/söz yazarı'),
  (23,'adlı besteci/söz yazarı'),
  (24,'adlı besteci/söz yazarı'),
  (26,'adlı besteci/söz yazarı'),
  (28,'adlı besteci/söz yazarı'),
  (31,'adlı besteci/söz yazarı'),
  (32,'adlı besteci/söz yazarı'),
  (33,'adlı besteci/söz yazarı'),
  (37,'adlı besteci/söz yazarı'),
  (39,'adlı besteci/söz yazarı'),
  (48,'adlı besteci/söz yazarı'),
  (49,'adlı besteci/söz yazarı'),
  (50,'adlı besteci/söz yazarı'),
  (52,'adlı besteci/söz yazarı'),
  (53,'adlı besteci/söz yazarı'),
  (54,'adlı besteci/söz yazarı'),
  (57,'adlı besteci/söz yazarı'),
  (58,'adlı besteci/söz yazarı'),
  (59,'adlı besteci/söz yazarı'),
  (61,'adlı besteci/söz yazarı'),
  (62,'adlı besteci/söz yazarı'),
  (64,'adlı besteci/söz yazarı'),
  (65,'adlı besteci/söz yazarı'),
  (68,'adlı besteci/söz yazarı'),
  (72,'adlı besteci/söz yazarı'),
  (73,'adlı besteci/söz yazarı'),
  (74,'adlı besteci/söz yazarı'),
  (75,'adlı besteci/söz yazarı'),
  (76,'adlı besteci/söz yazarı'),
  (79,'adlı besteci/söz yazarı'),
  (80,'adlı besteci/söz yazarı'),
  (81,'adlı besteci/söz yazarı'),
  (82,'adlı besteci/söz yazarı'),
  (83,'adlı besteci/söz yazarı'),
  (86,'adlı besteci/söz yazarı'),
  (87,'adlı besteci/söz yazarı'),
  (88,'adlı besteci/söz yazarı'),
  (92,'adlı besteci/söz yazarı'),
  (93,'adlı besteci/söz yazarı'),
  (94,'adlı besteci/söz yazarı'),
  (95,'adlı besteci/söz yazarı'),
  (97,'adlı besteci/söz yazarı'),
  (98,'adlı besteci/söz yazarı'),
  (99,'adlı besteci/söz yazarı'),
  (100,'adlı besteci/söz yazarı'),
  (104,'adlı besteci/söz yazarı'),
  (105,'adlı besteci/söz yazarı'),
  (106,'adlı besteci/söz yazarı'),
  (109,'adlı besteci/söz yazarı'),
  (111,'adlı besteci/söz yazarı'),
  (113,'adlı besteci/söz yazarı'),
  (114,'adlı besteci/söz yazarı'),
  (115,'adlı besteci/söz yazarı'),
  (116,'adlı besteci/söz yazarı'),
  (117,'adlı besteci/söz yazarı'),
  (118,'adlı besteci/söz yazarı'),
  (120,'adlı besteci/söz yazarı'),
  (122,'adlı besteci/söz yazarı'),
  (125,'adlı besteci/söz yazarı'),
  (126,'adlı besteci/söz yazarı'),
  (135,'adlı besteci/söz yazarı'),
  (139,'adlı besteci/söz yazarı'),
  (140,'adlı besteci/söz yazarı'),
  (144,'adlı besteci/söz yazarı'),
  (145,'adlı besteci/söz yazarı'),
  (147,'adlı besteci/söz yazarı'),
  (154,'adlı besteci/söz yazarı'),
  (156,'adlı besteci/söz yazarı'),
  (158,'adlı besteci/söz yazarı'),
  (160,'adlı besteci/söz yazarı'),
  (162,'adlı besteci/söz yazarı'),
  (166,'adlı besteci/söz yazarı'),
  (167,'adlı besteci/söz yazarı'),
  (170,'adlı besteci/söz yazarı'),
  (172,'adlı besteci/söz yazarı'),
  (173,'adlı besteci/söz yazarı'),
  (174,'adlı besteci/söz yazarı'),
  (176,'adlı besteci/söz yazarı'),
  (185,'adlı besteci/söz yazarı'),
  (187,'adlı besteci/söz yazarı'),
  (191,'adlı besteci/söz yazarı'),
  (198,'adlı besteci/söz yazarı'),
  (199,'adlı besteci/söz yazarı'),
  (200,'adlı besteci/söz yazarı'),
  (201,'adlı besteci/söz yazarı'),
  (202,'adlı besteci/söz yazarı'),
  (209,'adlı besteci/söz yazarı'),
  (218,'adlı besteci/söz yazarı'),
  (220,'adlı besteci/söz yazarı'),
  (221,'adlı besteci/söz yazarı'),
  (223,'adlı besteci/söz yazarı'),
  (224,'adlı besteci/söz yazarı'),
  (229,'adlı besteci/söz yazarı'),
  (231,'adlı besteci/söz yazarı'),
  (237,'adlı besteci/söz yazarı'),
  (238,'adlı besteci/söz yazarı'),
  (244,'adlı besteci/söz yazarı'),
  (247,'adlı besteci/söz yazarı'),
  (249,'adlı besteci/söz yazarı'),
  (252,'adlı besteci/söz yazarı'),
  (253,'adlı besteci/söz yazarı'),
  (254,'adlı besteci/söz yazarı'),
  (256,'adlı besteci/söz yazarı'),
  (278,'adlı besteci/söz yazarı'),
  (280,'adlı besteci/söz yazarı'),
  (282,'adlı besteci/söz yazarı'),
  (284,'adlı besteci/söz yazarı'),
  (285,'adlı besteci/söz yazarı'),
  (288,'adlı besteci/söz yazarı'),
  (291,'adlı besteci/söz yazarı'),
  (292,'adlı besteci/söz yazarı'),
  (295,'adlı besteci/söz yazarı'),
  (297,'adlı besteci/söz yazarı'),
  (298,'adlı besteci/söz yazarı'),
  (300,'adlı besteci/söz yazarı'),
  (301,'adlı besteci/söz yazarı'),
  (302,'adlı besteci/söz yazarı'),
  (304,'adlı besteci/söz yazarı'),
  (305,'adlı besteci/söz yazarı'),
  (312,'adlı besteci/söz yazarı'),
  (313,'adlı besteci/söz yazarı'),
  (318,'adlı besteci/söz yazarı'),
  (323,'adlı besteci/söz yazarı'),
  (326,'adlı besteci/söz yazarı'),
  (328,'adlı besteci/söz yazarı'),
  (334,'adlı besteci/söz yazarı'),
  (338,'adlı besteci/söz yazarı'),
  (339,'adlı besteci/söz yazarı'),
  (342,'adlı besteci/söz yazarı'),
  (343,'adlı besteci/söz yazarı'),
  (345,'adlı besteci/söz yazarı'),
  (346,'adlı besteci/söz yazarı'),
  (348,'adlı besteci/söz yazarı'),
  (349,'adlı besteci/söz yazarı'),
  (350,'adlı besteci/söz yazarı'),
  (351,'adlı besteci/söz yazarı'),
  (352,'adlı besteci/söz yazarı'),
  (355,'adlı besteci/söz yazarı'),
  (362,'adlı besteci/söz yazarı'),
  (363,'adlı besteci/söz yazarı'),
  (364,'adlı besteci/söz yazarı'),
  (365,'adlı besteci/söz yazarı'),
  (367,'adlı besteci/söz yazarı'),
  (368,'adlı besteci/söz yazarı'),
  (369,'adlı besteci/söz yazarı'),
  (370,'adlı besteci/söz yazarı'),
  (371,'adlı besteci/söz yazarı'),
  (374,'adlı besteci/söz yazarı'),
  (376,'adlı besteci/söz yazarı'),
  (377,'adlı besteci/söz yazarı'),
  (378,'adlı besteci/söz yazarı'),
  (388,'adlı besteci/söz yazarı'),
  (403,'adlı besteci/söz yazarı'),
  (404,'adlı besteci/söz yazarı'),
  (409,'adlı besteci/söz yazarı'),
  (410,'adlı besteci/söz yazarı'),
  (411,'adlı besteci/söz yazarı'),
  (412,'adlı besteci/söz yazarı'),
  (414,'adlı besteci/söz yazarı'),
  (415,'adlı besteci/söz yazarı'),
  (419,'adlı besteci/söz yazarı'),
  (420,'adlı besteci/söz yazarı'),
  (421,'adlı besteci/söz yazarı'),
  (422,'adlı besteci/söz yazarı'),
  (424,'adlı besteci/söz yazarı'),
  (425,'adlı besteci/söz yazarı'),
  (426,'adlı besteci/söz yazarı'),
  (436,'adlı besteci/söz yazarı'),
  (503,'adlı besteci/söz yazarı'),
  (506,'adlı besteci/söz yazarı'),
  (507,'adlı besteci/söz yazarı'),
  (513,'adlı besteci/söz yazarı'),
  (514,'adlı besteci/söz yazarı'),
  (515,'adlı besteci/söz yazarı'),
  (521,'adlı besteci/söz yazarı'),
  (523,'adlı besteci/söz yazarı'),
  (1928,'adlı besteci/söz yazarı'),
  (1941,'adlı besteci/söz yazarı')
)
insert into public.works_telif_yedek (work_id, lyrics, chords, nota_url, nota_pages, gizlendi_at, neden)
select w.id, w.lyrics, w.chords, w.nota_url, w.nota_pages, now(), l.neden
from liste l join public.works w on w.id = l.work_id
on conflict (work_id) do nothing;

update public.works w
   set lyrics = null, chords = null, nota_url = null, nota_pages = '[]'::jsonb
  from public.works_telif_yedek y
 where y.work_id = w.id
   and (w.lyrics is not null or w.chords is not null or w.nota_url is not null or w.nota_pages <> '[]'::jsonb);

-- GERİ AÇMA (yalnız lisans/izin alınan eserler; id'leri yaz):
--   update public.works w set lyrics = y.lyrics, chords = y.chords, nota_url = y.nota_url, nota_pages = y.nota_pages
--     from public.works_telif_yedek y where y.work_id = w.id and w.id in (...);
--   delete from public.works_telif_yedek where work_id in (...);
